# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170422_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='uestion_text',
            new_name='question_text',
        ),
    ]
